sonar.projectKey=swe5006-jiraffe
sonar.projectName=SWE5006 Jiraffe
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=.next/**,node_modules/**,coverage/**
